# mkdocs.yml
site_name: Medrag Multi Modal

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.tracking

plugins:
  - mkdocstrings
  - search
  - minify
  - glightbox
  - mkdocs-jupyter:
      include_source: True


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: 'index.md'
  - Setup:
    - Installation: 'installation/install.md'
    - Development: 'installation/development.md'
  - Document Loader:
    - Text Loader:
      - Base: 'document_loader/text_loader/base_text_loader.md'
      - PyMuPDF4LLM: 'document_loader/text_loader/pymupdf4llm_text_loader.md'
      - PyPDF2: 'document_loader/text_loader/pypdf2_text_loader.md'
      - PDFPlumber: 'document_loader/text_loader/pdfplumber_text_loader.md'
      - Marker: 'document_loader/text_loader/marker_text_loader.md'
    - Image Loader:
      - Base: 'document_loader/image_loader/base_img_loader.md'
      - PDF2Image: 'document_loader/image_loader/pdf2image_img_loader.md'
      - Marker: 'document_loader/image_loader/marker_img_loader.md'
      - PDFPlumber: 'document_loader/image_loader/pdfplumber_img_loader.md'
      - PyMuPDF: 'document_loader/image_loader/pymupdf_img_loader.md'
      - FitzPIL: 'document_loader/image_loader/fitzpil_img_loader.md'
  - Chunking: 'chunking.md'
  - Retrieval:
    - Multi-Modal Retrieval: 'retreival/multi_modal_retrieval.md'

repo_url: https://github.com/soumik12345/medrag-multi-modal
