# mkdocs.yml
site_name: Medrag Multi Modal

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.tracking

plugins:
  - mkdocstrings
  - search
  - minify
  - glightbox
  - mkdocs-jupyter:
      include_source: True


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: 'index.md'
  - Setup:
    - Installation: 'installation/install.md'
    - Development: 'installation/development.md'
  - App:
    - MedQA Assistant: 'app.md'
  - Retrieval Augmented Generation:
    - Document Loader:
      - Text Loader:
        - Base: 'rag/document_loader/text_loader/base_text_loader.md'
        - PyMuPDF4LLM: 'rag/document_loader/text_loader/pymupdf4llm_text_loader.md'
        - PyPDF2: 'rag/document_loader/text_loader/pypdf2_text_loader.md'
        - PDFPlumber: 'rag/document_loader/text_loader/pdfplumber_text_loader.md'
        - Marker: 'rag/document_loader/text_loader/marker_text_loader.md'
      - Image Loader:
        - Base: 'rag/document_loader/image_loader/base_img_loader.md'
        - PDF2Image: 'rag/document_loader/image_loader/pdf2image_img_loader.md'
        - Marker: 'rag/document_loader/image_loader/marker_img_loader.md'
        - PDFPlumber: 'rag/document_loader/image_loader/pdfplumber_img_loader.md'
        - PyMuPDF: 'rag/document_loader/image_loader/pymupdf_img_loader.md'
        - FitzPIL: 'rag/document_loader/image_loader/fitzpil_img_loader.md'
    - Chunking: 'rag/chunking.md'
    - Retrieval:
      - Text-only Retrieval:
        - BM25-Sparse: 'rag/retrieval/text_retrieval/bm25s.md'
        - Contriever: 'rag/retrieval/text_retrieval/contriever.md'
        - MedCPT: 'rag/retrieval/text_retrieval/medcpt.md'
        - Sentence-Transformers: 'rag/retrieval/text_retrieval/sentence_transformer.md'
      - ColPali: 'rag/retrieval/colpali.md'
    - Assistant:
      - MedQA Assistant: 'rag/assistant/medqa_assistant.md'
      - Figure Annotation: 'rag/assistant/figure_annotation.md'
      - LLM Client: 'rag/assistant/llm_client.md'
    - Eval:
      - Eval: 'rag/evals/eval.md'
      - Metrics:
        - Base: 'rag/evals/metrics/base.md'
        - MMLU: 'rag/evals/metrics/mmlu.md'

repo_url: https://github.com/soumik12345/medrag-multi-modal
