name: Tests
on:
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - medrag_multi_modal/**
      - pyproject.toml

jobs:
  code-format:
    name: check code format using black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
  lint:
    name: check linting using ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
  test-text-loader-pdfplumber:
    name: test text loader (pdfplumber)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -U uv pip
          uv venv
          source .venv/bin/activate
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[core, dev]"
          pytest -s tests/document_loader/text_loader.py::test_pdfplumber_text_loader
          deactivate
  test-text-loader-pymupdf4llm:
    name: test text loader (pymupdf4llm)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -U uv pip
          uv venv
          source .venv/bin/activate
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[core, dev]"
          pytest -s tests/document_loader/text_loader.py::test_pymupdf_text_loader
          deactivate
  test-text-loader-pypdf2:
    name: test text loader (pypdf2)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -U uv pip
          uv venv
          source .venv/bin/activate
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[core, dev]"
          pytest -s tests/document_loader/text_loader.py::test_pypdf2_text_loader
          deactivate
