name: Tests
on:
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - medrag_multi_modal/**
      - pyproject.toml

jobs:
  lint:
    name: check linting using ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
  test-text-loader-pdfplumber:
    name: test text loader (pdfplumber)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -U pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[core, dev]"
          pytest -s tests/document_loader/text_loader.py::test_pdfplumber_text_loader
          
  test-text-loader-pymupdf4llm:
    name: test text loader (pymupdf4llm)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -U pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[core, dev]"
          pytest -s tests/document_loader/text_loader.py::test_pymupdf_text_loader
          
  test-text-loader-pypdf2:
    name: test text loader (pypdf2)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -U pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[core, dev]"
          pytest -s tests/document_loader/text_loader.py::test_pypdf2_text_loader
          
  test-image-loader-fitzpil:
    name: test image loader (fitzpil)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get install -y poppler-utils
          pip install -U pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[core, dev]"
          pytest -s tests/document_loader/image_loader.py::test_fitzpil_img_loader
          
  test-image-loader-pdf2image:
    name: test image loader (pdf2image)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get install -y poppler-utils
          pip install -U pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[core, dev]"
          pytest -s tests/document_loader/image_loader.py::test_pdf2image_img_loader
          
  test-image-loader-pdfplumber:
    name: test image loader (pdfplumber)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get install -y poppler-utils
          pip install -U pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[core, dev]"
          pytest -s tests/document_loader/image_loader.py::test_pdfplumber_img_loader
          
  test-image-loader-pymupdf:
    name: test image loader (pymupdf)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get install -y poppler-utils
          pip install -U pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[core, dev]"
          pytest -s tests/document_loader/image_loader.py::test_pymupdf_img_loader
          
  test-semantic-chunking:
    name: test semantic chunking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get install -y poppler-utils
          pip install -U pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[core, dev]"
          pytest -s tests/semantic_chunking.py
          
  test-bm25s-retrieval:
    name: test retrieval (bm25s)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get install -y poppler-utils
          pip install -U pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[core, dev]"
          pytest -s tests/retrieval/test_bm25s.py
          
  test-contriever-retrieval:
    name: test retrieval (contriever)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get install -y poppler-utils
          pip install -U pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[core, dev]"
          pytest -s tests/retrieval/test_contriever.py
          
  test-medcpt-retrieval:
    name: test retrieval (medcpt)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get install -y poppler-utils
          pip install -U pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[core, dev]"
          pytest -s tests/retrieval/test_medcpt.py
          
  test-llm-client:
    name: test llm client
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -U pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[core, dev]"
          pytest -s tests/assistant/test_llm_client.py
