name: Tests
on:
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - medrag_multi_modal/**
      - pyproject.toml

jobs:
  code-format:
    name: check code format using black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
  lint:
    name: Check linting using ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
  test-text-loader:
    name: Test text loader
    runs-on: ubuntu-latest
    container: pytorch/pytorch
    steps:
      - uses: actions/checkout@v4
      - run: |
        pip install -U pip
        pip install -e ".[core, dev]"
        pytest -s tests/document_loader/text_loader.py
